"""
tool_registry.py — Canonical Gigi tool definitions and channel filters.

Single source of truth for all Gigi tool schemas. Imported by telegram_bot.py,
ringcentral_bot.py, and voice_brain.py.

Usage:
    from gigi.tool_registry import CANONICAL_TOOLS, get_tools, SMS_EXCLUDE

    ANTHROPIC_TOOLS = CANONICAL_TOOLS           # Telegram / ask-gigi
    sms_tools = get_tools("sms")               # RC SMS
    dm_tools  = get_tools("dm")                # RC DM / Team
    voice_tools = get_tools("voice")           # Retell voice
"""

# ============================================================
# CANONICAL TOOL DEFINITIONS  (Anthropic format)
# Single source of truth.  Add new tools HERE — not in
# telegram_bot.py, ringcentral_bot.py, or voice_brain.py.
# ============================================================

CANONICAL_TOOLS = [
    # === CHIEF-OF-STAFF / ENTERTAINMENT ===
    {"name": "search_events", "description": "Search events on Ticketmaster: concerts, sports (Avalanche, Nuggets, Broncos), theater, comedy. Returns structured event data with dates, venues, prices, and ticket links. Use this for ANY event search.", "input_schema": {"type": "object", "properties": {"query": {"type": "string", "description": "Artist, team, or event keyword (e.g. 'Colorado Avalanche', 'Phish', 'comedy')"}, "city": {"type": "string", "description": "City name (default Denver)"}, "state": {"type": "string", "description": "State code (default CO)"}, "start_date": {"type": "string", "description": "Start date YYYY-MM-DD (default today)"}, "end_date": {"type": "string", "description": "End date YYYY-MM-DD (default 30 days out)"}, "limit": {"type": "integer", "description": "Max events to return (default 10)"}}, "required": ["query"]}},
    {"name": "search_concerts", "description": "Alias for search_events — prefer search_events instead.", "input_schema": {"type": "object", "properties": {"query": {"type": "string", "description": "Search query"}}, "required": ["query"]}},
    {"name": "buy_tickets_request", "description": "Buy concert tickets (requires 2FA).", "input_schema": {"type": "object", "properties": {"artist": {"type": "string"}, "venue": {"type": "string"}, "quantity": {"type": "integer"}}, "required": ["artist", "venue"]}},
    {"name": "book_table_request", "description": "Book a restaurant reservation (requires 2FA).", "input_schema": {"type": "object", "properties": {"restaurant": {"type": "string"}, "party_size": {"type": "integer"}, "date": {"type": "string"}, "time": {"type": "string"}}, "required": ["restaurant", "party_size", "date", "time"]}},
    {"name": "explore_national_parks", "description": "Search the National Park Service API. Get park info, campgrounds, alerts, things to do, visitor centers, events, tours, webcams, amenities, and fees for any US national park.", "input_schema": {"type": "object", "properties": {"action": {"type": "string", "description": "parks, campgrounds, alerts, thingstodo, visitorcenters, events, tours, webcams, amenities, or fees"}, "query": {"type": "string", "description": "Search text (for parks action — e.g. 'Rocky Mountain', 'Yellowstone')"}, "park_code": {"type": "string", "description": "NPS park code (e.g. 'romo', 'yell', 'grca') — filters results to that park"}, "state": {"type": "string", "description": "State code to filter parks (e.g. 'CO', 'CA')"}, "limit": {"type": "integer", "description": "Max results (default 5, max 20)"}}, "required": ["action"]}},
    {"name": "explore_art", "description": "Search and explore artworks from museums worldwide. Search by artist, style, period, type, or get a random artwork. Returns titles, images, dates, and descriptions.", "input_schema": {"type": "object", "properties": {"action": {"type": "string", "description": "'search' (find artworks), 'detail' (get full info by ID), or 'random' (surprise me)"}, "query": {"type": "string", "description": "Search text — artist name, style, subject (e.g. 'Monet', 'impressionism', 'landscape')"}, "artwork_id": {"type": "integer", "description": "Artwork ID (for detail action)"}, "art_type": {"type": "string", "description": "Filter: painting, sculpture, drawing, photograph, print, textile, ceramic, etc."}, "origin": {"type": "string", "description": "Country or region (e.g. 'France', 'Japan', 'Italy')"}, "material": {"type": "string", "description": "Material filter (e.g. 'canvas', 'bronze', 'oil_paint', 'marble')"}, "earliest_year": {"type": "integer", "description": "Earliest creation year"}, "latest_year": {"type": "integer", "description": "Latest creation year"}, "limit": {"type": "integer", "description": "Max results 1-10 (default 5)"}}, "required": ["action"]}},
    {"name": "search_phish", "description": "Search the Phish.in archive — shows, setlists, songs, tours, venues with audio recordings. Get setlists for any date, look up how many times a song was played, find recent shows, or browse tours/venues.", "input_schema": {"type": "object", "properties": {"action": {"type": "string", "description": "'shows' (recent/all shows), 'show' (specific date setlist+tracks), 'song' (song stats), 'songs' (browse songs), 'tours', or 'venues'"}, "date": {"type": "string", "description": "Show date YYYY-MM-DD (for 'show' action)"}, "query": {"type": "string", "description": "Song name or search text"}, "song_slug": {"type": "string", "description": "Song slug (e.g. 'tweezer', 'you-enjoy-myself')"}, "limit": {"type": "integer", "description": "Max results (default 5)"}}, "required": ["action"]}},
    {"name": "search_books", "description": "Search Google Books for book recommendations, reviews, and details. Find books by title, author, subject, or ISBN. Get ratings, descriptions, page counts, and preview links.", "input_schema": {"type": "object", "properties": {"action": {"type": "string", "description": "'search' (find books) or 'detail' (full info by book ID)"}, "query": {"type": "string", "description": "Search text — title, topic, keywords (e.g. 'best sci-fi novels', 'leadership books')"}, "author": {"type": "string", "description": "Filter by author name"}, "subject": {"type": "string", "description": "Filter by subject/category (e.g. 'fiction', 'business', 'history')"}, "isbn": {"type": "string", "description": "Search by ISBN"}, "book_id": {"type": "string", "description": "Google Books volume ID (for detail action)"}, "filter_type": {"type": "string", "description": "'ebooks', 'free-ebooks', or 'paid-ebooks'"}, "limit": {"type": "integer", "description": "Max results 1-20 (default 5)"}}, "required": ["action"]}},
    {"name": "search_nytimes", "description": "Search the New York Times — top stories, article search, best sellers, and most popular articles. Great for current news, market-moving stories, book recommendations, and trending topics.", "input_schema": {"type": "object", "properties": {"action": {"type": "string", "description": "'top_stories' (today's top news), 'search' (find articles by keyword), 'best_sellers' (NYT best seller list), 'best_seller_lists' (browse available lists), 'most_popular' (most viewed/emailed/shared)"}, "query": {"type": "string", "description": "Search keywords (for 'search' action) or popularity type: 'viewed'/'emailed'/'shared' (for 'most_popular')"}, "section": {"type": "string", "description": "News section for top_stories: home, world, us, politics, business, technology, science, health, sports, arts, books, opinion, travel, food"}, "period": {"type": "integer", "description": "Time period for most_popular: 1, 7, or 30 days"}, "begin_date": {"type": "string", "description": "Start date YYYY-MM-DD (for search)"}, "end_date": {"type": "string", "description": "End date YYYY-MM-DD (for search)"}, "list_name": {"type": "string", "description": "Best seller list slug: hardcover-fiction, hardcover-nonfiction, paperback-nonfiction, young-adult-hardcover, etc."}, "limit": {"type": "integer", "description": "Max results (default 5)"}}, "required": ["action"]}},
    {"name": "search_f1", "description": "Formula 1 data — standings, race results, qualifying, schedules, drivers, teams, circuits. Get current championship standings, next race info, last race results, full season calendar, and driver/team lookups.", "input_schema": {"type": "object", "properties": {"action": {"type": "string", "description": "'standings' (drivers championship), 'constructors_championship', 'next_race', 'last_race' (most recent results), 'race_results' (specific round), 'qualifying', 'schedule' (season calendar), 'drivers', 'driver' (search by name), 'teams', 'circuits'"}, "query": {"type": "string", "description": "Driver name to search (for 'driver' action)"}, "year": {"type": "integer", "description": "Season year (default: current)"}, "round_num": {"type": "integer", "description": "Race round number (for race_results/qualifying)"}, "limit": {"type": "integer", "description": "Max results (default 10)"}}, "required": ["action"]}},
    # === WELLSKY / OPERATIONS ===
    {"name": "get_client_current_status", "description": "Check who is with a client right now.", "input_schema": {"type": "object", "properties": {"client_name": {"type": "string", "description": "Name of the client"}}, "required": ["client_name"]}},
    {"name": "get_calendar_events", "description": "Get upcoming calendar events.", "input_schema": {"type": "object", "properties": {"days": {"type": "integer", "description": "Days to look ahead (1-7)"}}, "required": []}},
    {"name": "search_emails", "description": "Search Jason's Gmail.", "input_schema": {"type": "object", "properties": {"query": {"type": "string"}, "max_results": {"type": "integer"}}, "required": []}},
    {"name": "get_weather", "description": "Get current weather and forecast.", "input_schema": {"type": "object", "properties": {"location": {"type": "string", "description": "City and State"}}, "required": ["location"]}},
    {"name": "get_wellsky_clients", "description": "Search clients in WellSky.", "input_schema": {"type": "object", "properties": {"search_name": {"type": "string"}, "active_only": {"type": "boolean"}}, "required": []}},
    {"name": "get_wellsky_caregivers", "description": "Search caregivers in WellSky.", "input_schema": {"type": "object", "properties": {"search_name": {"type": "string"}, "active_only": {"type": "boolean"}}, "required": []}},
    {"name": "get_wellsky_shifts", "description": "Get shifts. Use get_wellsky_clients/caregivers first to find IDs.", "input_schema": {"type": "object", "properties": {"client_id": {"type": "string"}, "caregiver_id": {"type": "string"}, "days": {"type": "integer"}, "past_days": {"type": "integer"}, "open_only": {"type": "boolean"}}, "required": []}},
    {"name": "clock_in_shift", "description": "Clock a caregiver into their shift in WellSky. Use when a caregiver forgot to clock in or needs help. Look up their shift first with get_wellsky_shifts.", "input_schema": {"type": "object", "properties": {"appointment_id": {"type": "string", "description": "Shift/appointment ID from WellSky"}, "caregiver_name": {"type": "string", "description": "Caregiver name (for logging)"}, "notes": {"type": "string", "description": "Optional notes"}}, "required": ["appointment_id"]}},
    {"name": "clock_out_shift", "description": "Clock a caregiver out of their shift in WellSky. Use when a caregiver forgot to clock out or needs help. Look up their shift first with get_wellsky_shifts.", "input_schema": {"type": "object", "properties": {"appointment_id": {"type": "string", "description": "Shift/appointment ID from WellSky"}, "caregiver_name": {"type": "string", "description": "Caregiver name (for logging)"}, "notes": {"type": "string", "description": "Optional notes"}}, "required": ["appointment_id"]}},
    {"name": "find_replacement_caregiver", "description": "Find a replacement caregiver when someone calls out sick. Searches available caregivers, scores by fit, initiates SMS outreach. Use after a call-out when a shift needs coverage.", "input_schema": {"type": "object", "properties": {"shift_id": {"type": "string", "description": "Shift/appointment ID needing coverage"}, "original_caregiver_id": {"type": "string", "description": "WellSky ID of caregiver who called out"}, "reason": {"type": "string", "description": "Reason for calloff"}}, "required": ["shift_id", "original_caregiver_id"]}},
    # === WEB / RESEARCH ===
    {"name": "web_search", "description": "Search the internet for current information.", "input_schema": {"type": "object", "properties": {"query": {"type": "string"}}, "required": ["query"]}},
    {"name": "browse_webpage", "description": "Browse a webpage and extract its text content. Use for research, reading articles, checking websites.", "input_schema": {"type": "object", "properties": {"url": {"type": "string", "description": "URL to browse"}, "extract_links": {"type": "boolean", "description": "Also extract links (default false)"}}, "required": ["url"]}},
    {"name": "take_screenshot", "description": "Take a screenshot of a webpage. Returns the file path of the saved image.", "input_schema": {"type": "object", "properties": {"url": {"type": "string", "description": "URL to screenshot"}, "full_page": {"type": "boolean", "description": "Capture full scrollable page (default false)"}}, "required": ["url"]}},
    {"name": "deep_research", "description": "Run deep autonomous financial research using the Elite Trading platform's 40+ data tools and 9 AI agents. Use for ANY investment question: stock analysis, crypto, macro outlook, sector rotation, portfolio strategy, etc. Returns institutional-grade research with evidence and confidence level. Takes 30-120 seconds.", "input_schema": {"type": "object", "properties": {"question": {"type": "string", "description": "The financial research question to analyze in depth"}}, "required": ["question"]}},
    # === MARKET DATA ===
    {"name": "get_stock_price", "description": "Get stock price for a ticker.", "input_schema": {"type": "object", "properties": {"symbol": {"type": "string"}}, "required": ["symbol"]}},
    {"name": "get_crypto_price", "description": "Get cryptocurrency price.", "input_schema": {"type": "object", "properties": {"symbol": {"type": "string"}}, "required": ["symbol"]}},
    {"name": "get_polybot_status", "description": "Get Elite Trading Polybot status (PAPER MODE — not real money). Polybot runs 11 strategies on Polymarket prediction markets in paper/simulation mode. Shows simulated portfolio, paper P&L, mock positions, and strategy performance. Use to check how the paper trading strategies are performing. For LIVE real-money weather trading, use get_weather_arb_status instead.", "input_schema": {"type": "object", "properties": {}, "required": []}},
    {"name": "get_weather_arb_status", "description": "Get live status of weather trading bots: (1) Weather Sniper Bot (Polymarket) — LIVE real money, auto-snipes slam-dunk US temperature markets at daily 11:00 UTC open. (2) Kalshi bot — trades US temperature markets on Kalshi exchange. Use when asked about weather arb, weather bots, weather trading, temperature bets, weather sniper, Polymarket weather, or Kalshi weather.", "input_schema": {"type": "object", "properties": {}, "required": []}},
    # === CLAUDE CODE / TERMINAL ===
    {"name": "create_claude_task", "description": "Dispatch a code fix, debug, or investigation task to Claude Code on the Mac Mini. Claude Code will autonomously read files, edit code, run commands, and deploy fixes. USE THIS whenever Jason asks to fix, debug, investigate, check, or update any code or service. Write a detailed description.", "input_schema": {"type": "object", "properties": {"title": {"type": "string", "description": "Short task title"}, "description": {"type": "string", "description": "Detailed description: what's broken, error messages, which files/project, expected behavior"}, "priority": {"type": "string", "description": "urgent (broken service), high (important), normal (routine), low (nice-to-have)"}, "working_directory": {"type": "string", "description": "Project dir: /Users/shulmeister/mac-mini-apps/careassist-unified (default), /Users/shulmeister/mac-mini-apps/elite-trading-mcp, etc."}}, "required": ["title", "description"]}},
    {"name": "check_claude_task", "description": "Check the status/result of a Claude Code task. Call without task_id to check the most recent task.", "input_schema": {"type": "object", "properties": {"task_id": {"type": "integer", "description": "Task ID to check (omit for most recent)"}}, "required": []}},
    {"name": "run_claude_code", "description": "Execute a code/infrastructure task using Claude Code on the Mac Mini. Use for: fixing bugs, editing files, investigating errors, checking logs, running tests, restarting services, git operations, deploying changes. Claude Code autonomously reads/writes files and runs commands. Returns the result directly (synchronous, no polling needed). PREFER THIS over create_claude_task for immediate results.", "input_schema": {"type": "object", "properties": {"prompt": {"type": "string", "description": "What to do. Be specific — include error messages, file paths, expected behavior."}, "directory": {"type": "string", "description": "Project: careassist (default/staging), production, website, hesed, trading, weather-arb, kalshi, powderpulse, employee-portal, client-portal, status-dashboard, qbo-dashboard. Or full path."}, "model": {"type": "string", "description": "'sonnet' (default, fast) or 'opus' (complex tasks)."}}, "required": ["prompt"]}},
    {"name": "browse_with_claude", "description": "Browse a website using Claude Code + Chrome. Can read pages, fill forms, click buttons, extract data, navigate multi-page flows. Much more capable than browse_webpage. Use for checking websites, reading content, web UI interactions, form automation.", "input_schema": {"type": "object", "properties": {"task": {"type": "string", "description": "What to do in the browser. Be specific."}, "url": {"type": "string", "description": "Target URL (optional if task includes it)."}}, "required": ["task"]}},
    {"name": "run_terminal", "description": "Execute a shell command directly on the Mac Mini via headless terminal. INSTANT and FREE — no API cost. Use for quick commands: checking logs (tail), service status (launchctl list), git operations (git status/log/diff), file checks (ls, cat), restarting services (kill + KeepAlive), disk usage, process checks (ps, lsof). For complex multi-step tasks that need AI reasoning, use run_claude_code instead.", "input_schema": {"type": "object", "properties": {"command": {"type": "string", "description": "Shell command to execute (e.g. 'tail -20 ~/logs/gigi-server.log', 'launchctl list | grep careassist', 'git -C ~/mac-mini-apps/careassist-unified status')"}, "timeout": {"type": "integer", "description": "Timeout in seconds (default 30, max 120)"}}, "required": ["command"]}},
    # === MEMORY ===
    {"name": "save_memory", "description": "Save an important operational fact, caregiver pattern, client preference, or instruction to long-term memory. Use when something notable emerges that should be remembered across conversations.", "input_schema": {"type": "object", "properties": {"content": {"type": "string", "description": "The fact, pattern, or preference to save."}, "category": {"type": "string", "description": "Category: scheduling, caregiver, client, operations, communication, general"}, "importance": {"type": "string", "description": "high/medium/low"}}, "required": ["content", "category"]}},
    {"name": "recall_memories", "description": "Search long-term memory for saved preferences, facts, or instructions.", "input_schema": {"type": "object", "properties": {"category": {"type": "string"}, "search_text": {"type": "string"}}, "required": []}},
    {"name": "forget_memory", "description": "Archive a memory that is no longer relevant.", "input_schema": {"type": "object", "properties": {"memory_id": {"type": "string"}}, "required": ["memory_id"]}},
    {"name": "search_memory_logs", "description": "Search Gigi's daily operation logs for past activity, tool usage, failures. Use when asked 'what happened on...'", "input_schema": {"type": "object", "properties": {"query": {"type": "string", "description": "Keywords to search"}, "days_back": {"type": "integer", "description": "Days back to search (default 30)"}}, "required": ["query"]}},
    # === AR / FINANCE ===
    {"name": "get_ar_report", "description": "Get the QuickBooks accounts receivable aging report showing outstanding invoices and overdue amounts. Use when asked about AR, accounts receivable, outstanding invoices, or who owes money.", "input_schema": {"type": "object", "properties": {"detail_level": {"type": "string", "description": "Level of detail: 'summary' (default) or 'detailed' (full invoice list)"}}, "required": []}},
    # === MARKETING TOOLS ===
    {"name": "get_marketing_dashboard", "description": "Get an aggregated marketing snapshot across all channels: social media, ads, email. Use when asked about marketing performance, campaign results, or overall marketing metrics.", "input_schema": {"type": "object", "properties": {"date_range": {"type": "string", "description": "Time period: 'today', '7d', '30d', 'mtd', 'ytd', 'last_month' (default: '7d')"}}, "required": []}},
    {"name": "get_google_ads_report", "description": "Get Google Ads performance: spend, clicks, impressions, conversions, ROAS. Use when asked about ad spend or Google Ads.", "input_schema": {"type": "object", "properties": {"date_range": {"type": "string", "description": "Time period (default: '30d')"}}, "required": []}},
    {"name": "get_website_analytics", "description": "Get GA4 website analytics: traffic, sessions, conversions, bounce rate, engagement. Use when asked about website traffic or analytics.", "input_schema": {"type": "object", "properties": {"date_range": {"type": "string", "description": "Time period (default: '7d')"}}, "required": []}},
    {"name": "get_social_media_report", "description": "Get social media metrics from Facebook, Instagram, LinkedIn, and Pinterest. Use when asked about social media performance.", "input_schema": {"type": "object", "properties": {"date_range": {"type": "string", "description": "Time period (default: '7d')"}, "platform": {"type": "string", "description": "Filter to one platform: 'facebook', 'instagram', 'linkedin', 'pinterest' (default: all)"}}, "required": []}},
    {"name": "get_gbp_report", "description": "Get Google Business Profile metrics: reviews, calls, direction requests, search appearances. Use when asked about GBP, Google reviews, or local SEO.", "input_schema": {"type": "object", "properties": {"date_range": {"type": "string", "description": "Time period (default: '30d')"}}, "required": []}},
    {"name": "get_email_campaign_report", "description": "Get email marketing metrics from Brevo: campaigns sent, open rate, click rate, deliverability. Use when asked about email campaigns or newsletters.", "input_schema": {"type": "object", "properties": {"date_range": {"type": "string", "description": "Time period (default: '30d')"}}, "required": []}},
    {"name": "generate_social_content", "description": "Generate social media content using Predis AI. Creates posts with images for Facebook, Instagram, etc. Use when Jason asks to create a social media post.", "input_schema": {"type": "object", "properties": {"prompt": {"type": "string", "description": "What the post should be about"}, "media_type": {"type": "string", "description": "Content type: 'single_image' (default), 'carousel', 'video', 'quote'"}}, "required": ["prompt"]}},
    # === FINANCE TOOLS ===
    {"name": "get_pnl_report", "description": "Get the Profit & Loss (income statement) from QuickBooks. Shows revenue, expenses, and net income. Use when asked about P&L, profitability, revenue, or expenses.", "input_schema": {"type": "object", "properties": {"period": {"type": "string", "description": "Period: 'ThisMonth', 'LastMonth', 'ThisQuarter', 'ThisYear', 'LastYear' (default: 'ThisMonth')"}}, "required": []}},
    {"name": "get_balance_sheet", "description": "Get the Balance Sheet from QuickBooks. Shows assets, liabilities, and equity. Use when asked about the balance sheet or company net worth.", "input_schema": {"type": "object", "properties": {"as_of_date": {"type": "string", "description": "Date in YYYY-MM-DD format (default: today)"}}, "required": []}},
    {"name": "get_invoice_list", "description": "Get the list of open or overdue invoices from QuickBooks. Shows who owes money and how much.", "input_schema": {"type": "object", "properties": {"status": {"type": "string", "description": "'Open' (unpaid, default), 'Overdue', or 'All'"}}, "required": []}},
    {"name": "get_cash_position", "description": "Get current cash position and runway estimate. Shows cash on hand, monthly net income/burn, and months of runway.", "input_schema": {"type": "object", "properties": {}, "required": []}},
    {"name": "get_financial_dashboard", "description": "Get a complete financial snapshot: AR aging, cash position, P&L summary, and invoice overview.", "input_schema": {"type": "object", "properties": {}, "required": []}},
    {"name": "get_subscription_audit", "description": "Audit all recurring charges and subscriptions. Groups expenses by vendor, identifies recurring patterns, and shows estimated monthly/annual cost. Use when asked about subscriptions, recurring charges, what we're paying for, or what to cancel.", "input_schema": {"type": "object", "properties": {"months_back": {"type": "integer", "description": "How many months of history to analyze (default: 6)"}}, "required": []}},
    # === THINKING TOOLS ===
    {"name": "sequential_thinking", "description": "Think through a complex problem step by step. Use for investigations, debugging, planning, or any multi-step reasoning. Each call is one thought in a chain. You can revise earlier thoughts or branch into alternative hypotheses. ALWAYS use this before diving into complex tasks — think first, act second.", "input_schema": {"type": "object", "properties": {"thought": {"type": "string", "description": "Your current thinking step — what you're considering, analyzing, or concluding"}, "thought_number": {"type": "integer", "description": "Current thought step number (start at 1)"}, "total_thoughts": {"type": "integer", "description": "Estimated total thoughts needed (can increase later)"}, "next_thought_needed": {"type": "boolean", "description": "Whether you need another thinking step after this one"}, "is_revision": {"type": "boolean", "description": "Set true if you're reconsidering an earlier thought"}, "revises_thought": {"type": "integer", "description": "Which thought number you're revising"}, "branch_from_thought": {"type": "integer", "description": "Thought number to branch from (for exploring alternative hypotheses)"}, "branch_id": {"type": "string", "description": "Label for this branch (e.g. 'dns-issue', 'db-bottleneck')"}}, "required": ["thought", "thought_number", "total_thoughts", "next_thought_needed"]}},
    {"name": "get_thinking_summary", "description": "Get the full chain of sequential thoughts for the current investigation. Shows all reasoning steps, revisions, and branches.", "input_schema": {"type": "object", "properties": {}, "required": []}},
    # === KNOWLEDGE GRAPH TOOLS ===
    {"name": "update_knowledge_graph", "description": "Update Gigi's knowledge graph — add or remove entities (people, organizations, places, things), relations between them, and observations (facts) about them. Use to build structured knowledge about the world: who works where, who cares for whom, what tools connect to what. The graph complements flat memories with relationship-aware storage.", "input_schema": {"type": "object", "properties": {"action": {"type": "string", "description": "add_entities | add_relations | add_observations | delete_entities | delete_relations | delete_observations"}, "entities": {"type": "array", "description": "For add_entities: list of {name, entityType, observations[]}", "items": {"type": "object", "properties": {"name": {"type": "string"}, "entityType": {"type": "string", "description": "person, caregiver, client, organization, place, software, service, etc."}, "observations": {"type": "array", "items": {"type": "string"}}}, "required": ["name", "entityType"]}}, "relations": {"type": "array", "description": "For add_relations/delete_relations: list of {from, to, relationType}", "items": {"type": "object", "properties": {"from": {"type": "string"}, "to": {"type": "string"}, "relationType": {"type": "string", "description": "Active voice: owns, works_for, cares_for, lives_in, manages, uses, etc."}}, "required": ["from", "to", "relationType"]}}, "observations": {"type": "array", "description": "For add_observations/delete_observations: list of {entityName, contents[]}", "items": {"type": "object", "properties": {"entityName": {"type": "string"}, "contents": {"type": "array", "items": {"type": "string"}}}, "required": ["entityName", "contents"]}}, "entity_names": {"type": "array", "description": "For delete_entities: names to remove", "items": {"type": "string"}}}, "required": ["action"]}},
    {"name": "query_knowledge_graph", "description": "Query Gigi's knowledge graph to find entities, their observations, and relationships. Use to answer questions about who does what, who's connected to whom, and what you know about a person/place/thing.", "input_schema": {"type": "object", "properties": {"action": {"type": "string", "description": "search (by keyword) | open_nodes (by exact names) | read_graph (full dump)"}, "query": {"type": "string", "description": "Search text — matches entity names, types, and observations (for search action)"}, "names": {"type": "array", "description": "Exact entity names to retrieve (for open_nodes action)", "items": {"type": "string"}}}, "required": ["action"]}},
    # === GOOGLE MAPS TOOLS ===
    {"name": "get_directions", "description": "Get driving directions, distance, and travel time between two locations. Use for 'how far is X from Y?', 'directions to...', caregiver-to-client commute estimates. Supports driving, transit, walking, bicycling.", "input_schema": {"type": "object", "properties": {"origin": {"type": "string", "description": "Start address or place name (e.g. '123 Main St, Aurora, CO' or 'Denver International Airport')"}, "destination": {"type": "string", "description": "End address or place name"}, "mode": {"type": "string", "description": "Travel mode: driving (default), transit, walking, bicycling"}}, "required": ["origin", "destination"]}},
    {"name": "geocode_address", "description": "Geocode an address to get coordinates, or validate/normalize an address. Returns formatted address, latitude, longitude, city, state, zip.", "input_schema": {"type": "object", "properties": {"address": {"type": "string", "description": "Address to geocode (e.g. '123 Main St, Denver, CO')"}}, "required": ["address"]}},
    {"name": "search_nearby_places", "description": "Find nearby places of a given type around a location. Use for 'find pharmacies near Mrs. Johnson', 'hospitals near this address', 'grocery stores in Aurora'. Supports: pharmacy, hospital, doctor, grocery, restaurant, gas station, bank, post office, park, gym, dentist, church, school, police, fire station, and more.", "input_schema": {"type": "object", "properties": {"location": {"type": "string", "description": "Address or place name to search around"}, "place_type": {"type": "string", "description": "Type of place — pharmacy, hospital, doctor, grocery, restaurant, gas station, bank, etc."}, "radius_miles": {"type": "integer", "description": "Search radius in miles (default 5, max 31)"}}, "required": ["location", "place_type"]}},
    # === GOOGLE WORKSPACE ADMIN (GAM) — READ ONLY ===
    {"name": "query_workspace", "description": "Query Google Workspace admin data using GAM. READ-ONLY — can look up users, groups, domains, devices, reports. Cannot create, update, delete, or modify anything. Examples: 'info user jacob@coloradocareassist.com', 'print users', 'print groups', 'info domain', 'report users'.", "input_schema": {"type": "object", "properties": {"command": {"type": "string", "description": "GAM command WITHOUT the leading 'gam'. Examples: 'info user jason@coloradocareassist.com', 'print users fields name,email,suspended', 'print groups', 'info domain', 'report users parameters accounts:last_login_time'. Only read commands (info, print, show, report, check) are allowed."}}, "required": ["command"]}},
    # === FAX TOOLS ===
    {"name": "send_fax", "description": "Send a fax to a phone number. Provide a publicly accessible URL to a PDF document.", "input_schema": {"type": "object", "properties": {"to": {"type": "string", "description": "Recipient fax number (e.g. 719-555-1234)"}, "media_url": {"type": "string", "description": "Public URL to the PDF document to fax"}}, "required": ["to", "media_url"]}},
    {"name": "list_faxes", "description": "List recent sent and received faxes.", "input_schema": {"type": "object", "properties": {"direction": {"type": "string", "description": "Filter: inbound, outbound, or all (default)"}, "limit": {"type": "integer", "description": "Max results (default 10)"}}, "required": []}},
    {"name": "read_fax", "description": "Read and AI-parse a received fax. Scans the PDF with AI to identify document type (facesheet, referral, authorization) and extract patient info, insurance, referral source, diagnosis. Use the fax 'id' from list_faxes.", "input_schema": {"type": "object", "properties": {"fax_id": {"type": "integer", "description": "Fax ID from list_faxes results"}}, "required": ["fax_id"]}},
    {"name": "file_fax_referral", "description": "File a fax referral: parses the fax, matches to existing WellSky client or creates a new prospect, and uploads the PDF to Google Drive. Use after read_fax confirms it's a referral/facesheet.", "input_schema": {"type": "object", "properties": {"fax_id": {"type": "integer", "description": "Fax ID to file"}}, "required": ["fax_id"]}},
    # === TASK MANAGEMENT ===
    {"name": "get_task_board", "description": "Read Jason's task board. Shows all tasks organized by section: Today, Soon, Later, Waiting, Agenda, Inbox, Done, Reference. Use when asked 'what's on my plate?', 'what do I have to do?', 'what's on the task board?', or to check current priorities before making recommendations.", "input_schema": {"type": "object", "properties": {}, "required": []}},
    {"name": "add_task", "description": "Add a task to Jason's task board. Use when Jason says 'I have a task', 'add to my list', 'remind me to', 'I need to', 'put X on my board', or any variation of wanting to capture a to-do. Default section is 'Today' for urgent/immediate, 'Soon' for this week, 'Later' for someday, 'Inbox' for unsorted.", "input_schema": {"type": "object", "properties": {"task": {"type": "string", "description": "The task description"}, "section": {"type": "string", "description": "Board section: Today, Soon, Later, Waiting, Agenda, Inbox (default: Today)"}}, "required": ["task"]}},
    {"name": "complete_task", "description": "Mark a task as done on Jason's task board. Moves it to the Done section. Use when Jason says 'done with X', 'finished X', 'check off X', 'completed X'.", "input_schema": {"type": "object", "properties": {"task_text": {"type": "string", "description": "Text of the task to complete (partial match OK)"}}, "required": ["task_text"]}},
    {"name": "capture_note", "description": "Capture a quick note or idea to Jason's scratchpad. Use when Jason says 'I have an idea', 'note this', 'jot this down', 'quick thought', or shares a fleeting idea that needs to be captured before it's lost. The scratchpad is processed daily and cleared.", "input_schema": {"type": "object", "properties": {"note": {"type": "string", "description": "The note or idea to capture"}}, "required": ["note"]}},
    {"name": "get_daily_notes", "description": "Read today's daily notes for context on what Jason has been working on. Use for situational awareness.", "input_schema": {"type": "object", "properties": {"date": {"type": "string", "description": "Date in YYYY-MM-DD format (default: today)"}}, "required": []}},
    # === TICKET WATCHES ===
    {"name": "watch_tickets", "description": "Set up a ticket watch for an artist or event. Gigi will monitor Ticketmaster and AXS (via Bandsintown) and send Telegram alerts when tickets go on presale, general sale, or new events are listed. Use when Jason says 'watch for tickets', 'let me know when tickets drop', 'monitor tickets for', etc.", "input_schema": {"type": "object", "properties": {"artist": {"type": "string", "description": "Artist or event name to watch"}, "venue": {"type": "string", "description": "Specific venue to filter (optional, e.g. 'Red Rocks')"}, "city": {"type": "string", "description": "City to search (default: Denver)"}}, "required": ["artist"]}},
    {"name": "list_ticket_watches", "description": "List all active ticket watches — shows what artists/events Gigi is monitoring for ticket alerts.", "input_schema": {"type": "object", "properties": {}, "required": []}},
    {"name": "remove_ticket_watch", "description": "Stop watching for tickets on a specific watch. Use list_ticket_watches first to get the watch ID.", "input_schema": {"type": "object", "properties": {"watch_id": {"type": "integer", "description": "Watch ID to remove"}}, "required": ["watch_id"]}},
    # === TRAVEL TOOLS ===
    {"name": "search_flights", "description": "Search real-time flight prices and availability via Amadeus. ALWAYS use this for flight queries — never use web_search for flights.", "input_schema": {"type": "object", "properties": {"origin": {"type": "string", "description": "Departure city or IATA code (e.g. Denver or DEN)"}, "destination": {"type": "string", "description": "Arrival city or IATA code (e.g. Honolulu or HNL)"}, "departure_date": {"type": "string", "description": "Departure date YYYY-MM-DD"}, "return_date": {"type": "string", "description": "Return date YYYY-MM-DD (omit for one-way)"}, "adults": {"type": "integer", "description": "Number of adult passengers (default 1)"}, "max_stops": {"type": "integer", "description": "Max stops: 0=direct only, 1=1 stop max (default 1)"}, "travel_class": {"type": "string", "description": "ECONOMY, PREMIUM_ECONOMY, BUSINESS, or FIRST (optional)"}}, "required": ["origin", "destination", "departure_date"]}},
    {"name": "search_hotels", "description": "Search hotel prices and availability via Amadeus. Returns hotel names, prices, room types, and offer IDs.", "input_schema": {"type": "object", "properties": {"city": {"type": "string", "description": "City name"}, "checkin": {"type": "string", "description": "Check-in date YYYY-MM-DD"}, "checkout": {"type": "string", "description": "Check-out date YYYY-MM-DD"}, "guests": {"type": "integer", "description": "Number of guests (default 2)"}, "max_price": {"type": "integer", "description": "Max price per night in cents (e.g. 20000 = $200)"}}, "required": ["city", "checkin", "checkout"]}},
    {"name": "search_car_rentals", "description": "Search car rental / ground transfer availability. Legacy — use search_transfers for new queries.", "input_schema": {"type": "object", "properties": {"pickup_location": {"type": "string", "description": "Pickup city or airport"}, "pickup_date": {"type": "string", "description": "Pickup date YYYY-MM-DD"}, "dropoff_date": {"type": "string", "description": "Dropoff date YYYY-MM-DD"}, "dropoff_location": {"type": "string", "description": "Different dropoff location (optional)"}, "car_class": {"type": "string", "description": "Car class: economy, compact, midsize, full-size, SUV, luxury (optional)"}}, "required": ["pickup_location", "pickup_date", "dropoff_date"]}},
    {"name": "search_transfers", "description": "Search ground transfers (airport pickups, private cars, shared shuttles) via Amadeus Transfer API.", "input_schema": {"type": "object", "properties": {"start_location": {"type": "string", "description": "Pickup airport IATA code (e.g. CDG, DEN)"}, "end_location": {"type": "string", "description": "Drop-off IATA code (if airport-to-airport)"}, "start_date_time": {"type": "string", "description": "Pickup datetime ISO format (e.g. 2026-04-01T10:00:00)"}, "passengers": {"type": "integer", "description": "Number of passengers (default 1)"}, "transfer_type": {"type": "string", "description": "PRIVATE or SHARED (default PRIVATE)"}, "end_address": {"type": "string", "description": "Drop-off street address (if not airport)"}, "end_city": {"type": "string", "description": "Drop-off city name"}, "end_country": {"type": "string", "description": "Drop-off country code (e.g. FR)"}}, "required": ["start_location", "start_date_time"]}},
    {"name": "get_flight_status", "description": "Get real-time flight status and delay prediction. Use for 'is my flight on time?' queries.", "input_schema": {"type": "object", "properties": {"carrier_code": {"type": "string", "description": "Airline IATA code (e.g. UA, DL, AA)"}, "flight_number": {"type": "string", "description": "Flight number (e.g. 319, 1234)"}, "departure_date": {"type": "string", "description": "Departure date YYYY-MM-DD"}, "predict_delay": {"type": "boolean", "description": "Also predict delay probability (default true)"}}, "required": ["carrier_code", "flight_number", "departure_date"]}},
    {"name": "explore_flights", "description": "Explore flight options: cheapest destinations from a city (origin only), cheapest dates for a route (origin+destination), or price analysis (origin+destination+date). Great for 'where should I fly?' or 'when is cheapest?'", "input_schema": {"type": "object", "properties": {"origin": {"type": "string", "description": "Departure IATA code (e.g. DEN)"}, "destination": {"type": "string", "description": "Arrival IATA code (omit for inspiration/cheapest destinations)"}, "departure_date": {"type": "string", "description": "YYYY-MM-DD (omit for cheapest dates, include for price analysis)"}, "currency": {"type": "string", "description": "Currency code (default USD)"}}, "required": ["origin"]}},
    {"name": "confirm_flight_price", "description": "Confirm/reprice a flight offer and optionally get branded fare upsell options. Use after search_flights to verify pricing before booking.", "input_schema": {"type": "object", "properties": {"flight_offer": {"type": "object", "description": "Raw flight offer dict from Amadeus search"}, "include_bags": {"type": "boolean", "description": "Include baggage fee info"}, "include_branded_fares": {"type": "boolean", "description": "Also return branded fare alternatives (Economy Light, Flex, Business)"}}, "required": ["flight_offer"]}},
    {"name": "get_seatmap", "description": "Get seatmap/seat availability for a flight offer or booked order.", "input_schema": {"type": "object", "properties": {"flight_offer": {"type": "object", "description": "Raw flight offer dict"}, "flight_order_id": {"type": "string", "description": "Order ID from a booking (alternative to flight_offer)"}}, "required": []}},
    {"name": "search_flight_availability", "description": "Search flight seat availability by fare class. Shows how many seats are available in each booking class.", "input_schema": {"type": "object", "properties": {"origin": {"type": "string", "description": "Departure IATA code"}, "destination": {"type": "string", "description": "Arrival IATA code"}, "departure_date": {"type": "string", "description": "YYYY-MM-DD"}, "adults": {"type": "integer", "description": "Number of passengers (default 1)"}, "travel_class": {"type": "string", "description": "ECONOMY, PREMIUM_ECONOMY, BUSINESS, FIRST (optional)"}}, "required": ["origin", "destination", "departure_date"]}},
    {"name": "book_flight", "description": "Book a flight (create order). Currently sandbox mode — test bookings only.", "input_schema": {"type": "object", "properties": {"flight_offer": {"type": "object", "description": "Flight offer from search/pricing"}, "travelers": {"type": "array", "description": "List of traveler objects with name, dateOfBirth, gender, contact, documents"}}, "required": ["flight_offer", "travelers"]}},
    {"name": "manage_flight_booking", "description": "Retrieve or cancel a flight booking by order ID.", "input_schema": {"type": "object", "properties": {"order_id": {"type": "string", "description": "Flight order ID"}, "action": {"type": "string", "description": "get or cancel (default get)"}}, "required": ["order_id"]}},
    {"name": "get_airport_info", "description": "Get airport/city info: search by keyword, find nearest airports, get direct routes, or check on-time performance.", "input_schema": {"type": "object", "properties": {"action": {"type": "string", "description": "search, nearest, routes, or performance"}, "query": {"type": "string", "description": "Search keyword (for action=search)"}, "airport_code": {"type": "string", "description": "IATA code (for routes/performance)"}, "latitude": {"type": "number", "description": "Latitude (for nearest)"}, "longitude": {"type": "number", "description": "Longitude (for nearest)"}, "date": {"type": "string", "description": "YYYY-MM-DD (for performance)"}}, "required": ["action"]}},
    {"name": "get_airline_info", "description": "Get airline info: lookup airline details, see all destinations served, or get online check-in links.", "input_schema": {"type": "object", "properties": {"action": {"type": "string", "description": "lookup, routes, or checkin"}, "airline_code": {"type": "string", "description": "IATA airline code (e.g. UA, DL, AA)"}}, "required": ["action", "airline_code"]}},
    {"name": "get_hotel_ratings", "description": "Get hotel sentiment analysis and ratings from guest reviews.", "input_schema": {"type": "object", "properties": {"hotel_ids": {"type": "string", "description": "Comma-separated Amadeus hotel IDs (max 3)"}}, "required": ["hotel_ids"]}},
    {"name": "book_hotel", "description": "Book a hotel room. Currently sandbox mode — test bookings only.", "input_schema": {"type": "object", "properties": {"offer_id": {"type": "string", "description": "Hotel offer ID from search_hotels results"}, "guests": {"type": "array", "description": "List of guest objects with name and contact"}, "payment": {"type": "object", "description": "Payment object with card details"}}, "required": ["offer_id", "guests", "payment"]}},
    {"name": "book_transfer", "description": "Book a ground transfer. Currently sandbox mode — test bookings only.", "input_schema": {"type": "object", "properties": {"offer_id": {"type": "string", "description": "Transfer offer ID from search_transfers"}, "passengers": {"type": "array", "description": "List of passenger objects"}, "payment": {"type": "object", "description": "Payment object (optional)"}}, "required": ["offer_id", "passengers"]}},
    {"name": "manage_transfer", "description": "Cancel a transfer booking.", "input_schema": {"type": "object", "properties": {"order_id": {"type": "string", "description": "Transfer order ID"}, "confirm_number": {"type": "string", "description": "Confirmation number from booking"}}, "required": ["order_id", "confirm_number"]}},
    {"name": "search_activities", "description": "Search tours and activities at a destination. Great for 'what can I do in Paris?' queries.", "input_schema": {"type": "object", "properties": {"city": {"type": "string", "description": "City name (e.g. Paris, Tokyo)"}, "latitude": {"type": "number", "description": "Latitude (alternative to city)"}, "longitude": {"type": "number", "description": "Longitude (alternative to city)"}, "radius": {"type": "integer", "description": "Search radius in km"}}, "required": []}},
    {"name": "get_travel_insights", "description": "Get travel market insights: most popular destinations, busiest travel periods, destination recommendations, or trip purpose prediction.", "input_schema": {"type": "object", "properties": {"action": {"type": "string", "description": "most_traveled, most_booked, busiest_period, recommendations, or trip_purpose"}, "origin": {"type": "string", "description": "Origin city IATA (for most_traveled/booked/recommendations)"}, "city": {"type": "string", "description": "City IATA (for busiest_period)"}, "period": {"type": "string", "description": "YYYY-MM or YYYY"}, "destination": {"type": "string", "description": "Destination IATA (for trip_purpose)"}, "departure_date": {"type": "string", "description": "YYYY-MM-DD (for trip_purpose)"}, "return_date": {"type": "string", "description": "YYYY-MM-DD (for trip_purpose)"}, "country_code": {"type": "string", "description": "Country code (default US)"}}, "required": ["action"]}},
]

# ============================================================
# CHANNEL FILTER SETS
# ============================================================

# Tools excluded from SMS (caregivers don't need these; also Gemini schema limitations)
SMS_EXCLUDE = {
    "get_marketing_dashboard", "get_google_ads_report", "get_website_analytics",
    "get_social_media_report", "get_gbp_report", "get_email_campaign_report",
    "generate_social_content", "get_pnl_report", "get_balance_sheet",
    "get_invoice_list", "get_cash_position", "get_financial_dashboard",
    "get_subscription_audit",
    "run_claude_code", "browse_with_claude",
    "browse_webpage", "take_screenshot", "deep_research",
    "get_polybot_status",
    "run_terminal",
    "sequential_thinking", "get_thinking_summary",
    "update_knowledge_graph", "query_knowledge_graph",
    "get_directions", "geocode_address", "search_nearby_places",
    "query_workspace",
    # Complex array schemas break Gemini tool conversion
    "book_flight", "book_hotel", "book_transfer", "confirm_flight_price",
    "search_flights", "search_hotels", "search_transfers", "search_activities",
    "get_flight_status", "get_seatmap", "search_flight_availability",
    "manage_flight_booking", "get_airport_info", "get_airline_info",
    "get_hotel_ratings", "manage_transfer", "explore_flights",
    "get_travel_insights", "search_car_rentals",
}

# Tools excluded from voice (browser/screenshot don't make sense via phone)
VOICE_EXCLUDE = {
    "browse_webpage", "take_screenshot", "browse_with_claude",
    "get_polybot_status",
}


def get_tools(channel: str) -> list:
    """Return the filtered tool list for a given channel.

    Args:
        channel: "telegram" | "sms" | "dm" | "voice"

    Returns:
        List of Anthropic-format tool dicts.
    """
    if channel in ("telegram", "dm"):
        return list(CANONICAL_TOOLS)
    elif channel == "sms":
        return [t for t in CANONICAL_TOOLS if t["name"] not in SMS_EXCLUDE]
    elif channel == "voice":
        return [t for t in CANONICAL_TOOLS if t["name"] not in VOICE_EXCLUDE]
    return list(CANONICAL_TOOLS)
